apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: audit-webhook.k8s.local
spec:
  kubeAPIServer:
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /etc/kubernetes/audit-policy.yaml
    auditWebhookConfigFile: /etc/kubernetes/audit-webhook.yaml
  fileAssets:
  - name: audit-policy
    # Note if not path is specificied the default path it /srv/kubernetes/assets/<name>
    path: /etc/kubernetes/audit-policy.yaml
    roles: [Master] # a list of roles to apply the asset to, zero defaults to all
    content: |
      apiVersion: audit.k8s.io/v1beta1
      kind: Policy
      # Don't generate audit events for all requests in RequestReceived stage.
      omitStages:
      - "RequestReceived"
      rules:
      - level: RequestResponse
        # users: ["system:serviceaccount:<namespace>:<serviceaccount-name>"]
        resources:
        - group: "" # core
          resources: ["pods", "secrets"]
        - group: "extensions"
          resources: ["deployments"]
  - name: audit-webhook
    # Note if not path is specificied the default path it /srv/kubernetes/assets/<name>
    path: /etc/kubernetes/audit-webhook.yaml
    roles: [Master] # a list of roles to apply the asset to, zero defaults to all
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - cluster:
          server: http://api.sharing.io:8080/events
        name: hit-config
      contexts:
      - context:
          cluster: hit-config
          user: ""
        name: webhook
      current-context: webhook
      users: []
      preferences: {}
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://ii-clusters/audit-webhook.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-australia-southeast1-c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-australia-southeast1-c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.audit-webhook.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: ii-coop
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: australia-southeast1
    region: australia-southeast1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: audit-webhook.k8s.local
  name: master-australia-southeast1-c
spec:
  image: cos-cloud/cos-stable-60-9592-90-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-australia-southeast1-c
  role: Master
  subnets:
  - australia-southeast1
  zones:
  - australia-southeast1-c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    audit-webhook.k8s.local
  name: nodes
spec:
  image: cos-cloud/cos-stable-60-9592-90-0
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - australia-southeast1
  zones:
  - australia-southeast1-c
