sig-release:
  sig-release-master-blocking:
    ci-kubernetes-e2e-gci-gce:
      - 34369
  sig-release-1.13-all:
    ci-kubernetes-e2e-gce-cos-k8sbeta-default:
      - 8843
  sig-release-1.12-all:
    ci-kubernetes-e2e-gce-cos-k8sstable1-default:
      - 5294
  sig-release-1.11-all:
    ci-kubernetes-e2e-gce-cos-k8sstable2-default:
      - 1789
  sig-release-1.10-all:
    ci-kubernetes-e2e-gce-cos-k8sstable3-default:
      - 446
# conformance:
#   conformance-gce:
#     ci-kubernetes-gce-conformance:
#       - 827
#     ci-kubernetes-gce-conformance-stable-1-12:
#       - 3
#       - 84
#     ci-kubernetes-gce-conformance-stable-1-11:
#       - 251
#     ci-kubernetes-gce-conformance-stable-1-10:
#       - 746
#     ci-kubernetes-gce-conformance-stable-1-9:
#       - 747
#     ci-kubernetes-gce-conformance-stable-1-8:
#       - 561
