sig-release:
    sig-release-1.10-all:
        ci-kubernetes-e2e-gce-cos-k8sstable3-default:
        - 1121083339638312961
    sig-release-1.11-all:
        ci-kubernetes-e2e-gce-cos-k8sstable2-default:
        - 1121457989778149377
    sig-release-1.12-all:
        ci-kubernetes-e2e-gce-cos-k8sstable1-default:
        - 1121581392354873344
    sig-release-1.13-all:
        ci-kubernetes-e2e-gce-cos-k8sbeta-default:
        - 1121564030004105216
    sig-release-master-blocking:
        ci-kubernetes-e2e-gci-gce:
        - 1121334929389522946
