- op: add
  path: /spec/rules/0/host
  value: "pgadmin.103.26.16.167.xip.io"
- op: add
  path: "/metadata/annotations/nginx.ingress.kubernetes.io~1server-alias"
  value: "pgadmin.localho.st pgadmin.local.ii.coop"

