kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  namespace: elasticsearch
  name: set-sysctl
  labels:
    app: set-sysctl
spec:
  template:
    metadata:
      labels:
        app: set-sysctl 
    spec:
      hostPID: true
      containers:
        - name: set-sysctl
          image: gcr.io/google-containers/startup-script:v1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: STARTUP_SCRIPT
            value: |
              #! /bin/bash
              sysctl -w vm.max_map_count=262144

              echo done
